"""Figures that survive black-and-white printing.

Shared by both studies. Lives here rather than being copied into each package,
because the copies had already begun to drift and every fix had to be applied
twice -- which is how one of them ends up stale.

These figures go into a printed manual, so colour is not a reliable channel.
Every categorical distinction therefore carries a *redundant* non-colour
encoding: bars get hatch patterns, lines get dash patterns and markers, scatter
points get marker shapes. Colour stays, because it helps on screen, but nothing
depends on it alone.

The palette is chosen for luminance separation as well as hue. Two colours that
look distinct on screen can converge to the same grey: matplotlib's default
``tab10`` blue (#1f77b4) and green (#2ca02c) sit at greyscale 0.42 and 0.45,
which is a 3% difference and invisible in print. ``check_separation`` asserts a
minimum gap so a future edit cannot silently reintroduce that problem, and
``save_grayscale_proof`` writes a desaturated copy of any figure so the print
appearance can actually be inspected rather than assumed.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

# --------------------------------------------------------------------------- #
# redundant encodings
# --------------------------------------------------------------------------- #
# Ordered so that adjacent entries are visually distinct at small sizes.
HATCHES = ("", "///", "...", "\\\\\\", "xxx", "|||", "---", "+++", "ooo", "***")

LINESTYLES = (
    "-",                    # solid
    (0, (5, 2)),            # dashed
    (0, (1, 1.2)),          # dotted
    (0, (6, 1.5, 1, 1.5)),  # dash-dot
    (0, (3, 1, 1, 1, 1, 1)),  # dash-dot-dot
    (0, (8, 2, 2, 2)),      # long dash short dash
    (0, (2, 2)),            # even dash
)

MARKERS = ("o", "s", "^", "D", "v", "P", "X", "*", "<", ">", "h")

# Luminance-separated palette, constructed rather than hand-picked.
#
# A first attempt chose colours by hue and asserted a clean luminance spread.
# Auditing it found six pairs closer than the threshold -- worse than
# matplotlib's tab10, which has one. Hues that look well separated on screen do
# not imply separated greys. These were instead generated by fixing seven target
# luminances evenly across 0.10-0.80 and searching hue/saturation for a vivid
# colour hitting each. Minimum pairwise greyscale gap: 0.110, against 0.032 for
# tab10. ``audit_palette`` re-derives these numbers so the claim stays checkable.
PALETTE = (
    "#1a1a1a",  # L=0.102  near-black
    "#163891",  # L=0.220  deep blue
    "#de1931",  # L=0.340  red
    "#bc37fb",  # L=0.459  violet
    "#f27821",  # L=0.575  orange
    "#37ecb6",  # L=0.689  aqua
    "#f5dd06",  # L=0.799  yellow
)


# Lines and markers sit on white, so the two lightest entries wash out even
# though they are perfectly legible as a bar fill (where the hatch and the dark
# edge supply contrast). Line plots draw from this darker subset and rely on
# dash pattern and marker shape to separate more than five series.
LINE_PALETTE = tuple(c for c in PALETTE if c not in ("#37ecb6", "#f5dd06"))


def luminance(color) -> float:
    """Perceived greyscale value of a colour in [0, 1] (BT.601 weights)."""
    import matplotlib.colors as mcolors

    r, g, b = mcolors.to_rgb(color)
    return 0.299 * r + 0.587 * g + 0.114 * b


def check_separation(colors, min_gap: float = 0.045) -> list[tuple]:
    """Colour pairs whose greyscale values are too close to tell apart.

    Returns the offending pairs rather than raising, so a caller can decide
    whether the pair is actually distinguished by hatch or dash instead.
    """
    lums = [(c, luminance(c)) for c in colors]
    bad = []
    for i in range(len(lums)):
        for j in range(i + 1, len(lums)):
            gap = abs(lums[i][1] - lums[j][1])
            if gap < min_gap:
                bad.append((lums[i][0], lums[j][0], round(gap, 4)))
    return bad


def line_color(i: int) -> str:
    """Colour for the i-th line series, from the darker subset."""
    return LINE_PALETTE[i % len(LINE_PALETTE)]


def style_for(i: int) -> dict:
    """Colour, hatch, dash and marker for the i-th category."""
    return {
        "color": PALETTE[i % len(PALETTE)],
        "line_color": line_color(i),
        "hatch": HATCHES[i % len(HATCHES)],
        "linestyle": LINESTYLES[i % len(LINESTYLES)],
        "marker": MARKERS[i % len(MARKERS)],
    }


# --------------------------------------------------------------------------- #
# appliers
# --------------------------------------------------------------------------- #
def hatch_bars(bars, offset: int = 0, edgecolor: str = "#1b1b1b", lw: float = 0.7):
    """Give each bar in a container a distinct hatch.

    Hatch density has to stay coarse: ``////`` at a small figure size renders as
    solid grey once rasterised at print DPI, which destroys the distinction it
    was meant to create.
    """
    for k, bar in enumerate(bars):
        bar.set_hatch(HATCHES[(k + offset) % len(HATCHES)])
        bar.set_edgecolor(edgecolor)
        bar.set_linewidth(lw)
    return bars


def hatch_grouped(containers, edgecolor: str = "#1b1b1b", lw: float = 0.7):
    """Hatch a grouped bar chart by *series*, so each series reads as one thing."""
    for s, cont in enumerate(containers):
        for bar in cont:
            bar.set_hatch(HATCHES[s % len(HATCHES)])
            bar.set_edgecolor(edgecolor)
            bar.set_linewidth(lw)
    return containers


def apply_print_rcparams(mpl):
    """Hatch linewidth and other print-relevant defaults."""
    mpl.rcParams.update({
        "hatch.linewidth": 0.8,
        "hatch.color": "#1a1a1a",
        "patch.linewidth": 0.7,
        "legend.handleheight": 1.4,
        "legend.handlelength": 2.8,
    })


def tidy_log_axis(ax, ticks, axis: str = "x"):
    """Label a log axis with only the values actually sampled.

    A log-scaled axis defaults to decade minor labels (3x10^1, 4x10^1 ...) which
    collide with the real tick labels and read as noise in print. Only the
    sampled scarcity levels mean anything here, so everything else is silenced.
    """
    import matplotlib.ticker as mticker

    a = ax.xaxis if axis == "x" else ax.yaxis
    a.set_major_locator(mticker.FixedLocator(list(ticks)))
    a.set_major_formatter(mticker.ScalarFormatter())
    a.set_minor_locator(mticker.NullLocator())
    a.set_minor_formatter(mticker.NullFormatter())
    return ax


# --------------------------------------------------------------------------- #
# verification
# --------------------------------------------------------------------------- #
def save_grayscale_proof(png_path: Path) -> Path | None:
    """Write a desaturated copy next to a figure, for checking print appearance.

    Cheap insurance: the greyscale version is what the manual will show, and it
    is the only way to confirm the redundant encodings actually did their job.
    """
    try:
        from PIL import Image
    except ImportError:
        return None
    png_path = Path(png_path)
    if not png_path.exists():
        return None
    out = png_path.with_name(png_path.stem + "_gray.png")
    Image.open(png_path).convert("RGB").convert("L").save(out)
    return out


def audit_palette(verbose: bool = True) -> dict:
    """Report the palette's greyscale spread and any colliding pairs."""
    lums = {c: round(luminance(c), 3) for c in PALETTE}
    bad = check_separation(PALETTE)
    if verbose:
        print("palette greyscale values:")
        for c, v in lums.items():
            print(f"  {c}  {v:.3f}  {'#' * int(v * 40)}")
        if bad:
            print("pairs closer than the threshold (must be separated by hatch/dash):")
            for a, b, g in bad:
                print(f"  {a} vs {b}: gap {g}")
        else:
            print("all pairs separable by luminance alone")
    return {"luminance": lums, "collisions": bad}
